### ISSUE TITLE
How can this bridge help to connect to Watson API?

### ISSUE THREAD

**Issue by omitobi** [findbrok/php-watson-api-bridge#10]
Sorry if the question sounds strange but indeed I attempted following the doc in order to connect to Watson Conversation API to no avail. In deed starting with creating new bridge and sending a request, I have got several error response.

Even when I do the following I still get some errors:

```
        $carpenter = app()->make(Carpenter::class);
        $bridge = $carpenter->constructBridge('default', 'conversation');

        $response = $bridge->get('uri');
```

My proposal is that the Doc is update to show it in steps how to connect to a service, because truthfully even though it seems the info is there but its just scattered on different lines and its hard to get them together. Great job though for creating this software. Now can someone show me how to simply connect to this service? Thanks.

**Comment by percymamedy** [comment]
Hi @omitobi 

Thank you for your appreciation. It is true the documentation is not that tough, as I haven't had time to update it yet. It is difficult to maintain open source software as time is a factor which affects us all.

To come back to your request. Could you please dump the error response that you are getting from Watson, so that we can help you understand and point out the problem.

Thanks

**Comment by omitobi** [comment]
@percymamedy Please pardon my delayed response. Indeed, I should have replied but because of the quick need to make things work, I simply used guzzle directly on Watson API. Truthfully, up till now I still believe I may be re-engineering the wheel since I do not know how much this package could alleviate the burden. However, I will attempt the same process again and see if I would still reproduce the issues; what ever I find out, I post it here as a comment. Once again, nice package and great job!
